### ISSUE TITLE
Client needs to be able to set connection and read timeouts

### ISSUE THREAD

**Issue by ramlow** [ibm-watson-iot/iot-java#131]
While investigating a load test hang, I noticed we stopped getting data from the JMeter test when we did a restart on the load balancer.   We debugged the problem and found that the JAVA API Client hangs and never returns if it sent a request and it looses the connection while waiting for the reply.   I looked at the Java API Client code but we could not find any way to set a timeout.   We believe this hang can be resolved if we were able to set a connection timeout and a read timeout in this client.

**Comment by miketran78727** [comment]
In many asynchronous calls (connect, disconnect, publish, subscribe), the client library is currently using `waitForCompletion()` without specifying a timeout value.   Therefore, the calling thread will block and may not return to the caller.

The fix is to add a new global property named `"ActionTimeout"`, in milliseconds which can be set by the application when instantiating the IoT client objects.  If the `"ActionTimeout"` property is not specified, the default timeout is 30 seconds.

Also new methods with a `timeout` parameter will be added for publishing/subscribing events and command.

**Comment by miketran78727** [comment]
Delivered changes to master branch
