### ISSUE TITLE
getEventsMappedToPhysicalInterface has wrong return type

### ISSUE THREAD

**Issue by Joern-Ploennigs** [ibm-watson-iot/iot-java#185]
Calling getEventsMappedToPhysicalInterface with a physical interface ID results in the error below
```
com.ibm.iotf.client.IoTFCReSTException: Failure in retrieving list of events associated with active physical interface ::Not a JSON Object: 
[{"eventId":"eventA","eventTypeId":"5e495119c05fff0009560d90"},{"eventId":"eventB","eventTypeId":"5e495118c05fff0009560d8f"}]
```

It makes sense that it should be returning JsonArray like getActiveLogicalInterfacesForDeviceType

**Comment by durera** [comment]
It looks like you are using the old `com.ibm.messaging/watson-iot` library, which has been completely replaced by `com.ibm.wiotp/com.ibm.wiotp.sdk`

https://mvnrepository.com/artifact/com.ibm.wiotp

Due to the overhead and limited benefit in maintaining a bespoke API client for the WIoTP APIs, the new version does not have equivalent features.  We recommend using your preferred Java HTTP requests client directly.  The APIs are documented here: https://docs.internetofthings.ibmcloud.com/apis/swagger/index.html

Authentication is simple HTTP Basic ... set username to your API key and password to the Token associated with that key :+1:
