### ISSUE TITLE
Q: is there a transition guide from 0.2.6?

### ISSUE THREAD

**Issue by akauppi** [ibm-watson-iot/iot-java#187]
I have a project to take from 0.2.6 to 0.4.0 and there are obvious differences in the API. 

Does IBM provide documentation about the changes?

**Comment by akauppi** [comment]
One observation of the 0.4.0 API is that while there is `.registerEventCallback` the same for status messages is `.setStatusCallback`.

**Comment by rdasgupt** [comment]
@akauppi 
Unfortunately documentation is incomplete. Work is still in progress. We will try to update the docs as soon as possible. Thanks for your patience.

**Comment by akauppi** [comment]
I think it starts to be too late for me. You are clearly doing a better job at the Python side so I'd suggest concentrating the efforts there.

For Java apps, consuming MQTT directly with e.g. Alpakka-MQTT is in my opinion a more maintainable approach. Just my 2c.

**Comment by durera** [comment]
Yup, any MQTT library can be used to connect to IoT platform.  As you rightly point out Python is our lead project, nodejs probably a close second, with Java somewhat struggling to gain development time and attention.

There is no migration guide between the old `com.ibm.messaging/watson-iot` library and `com.ibm.wiotp/com.ibm.wiotp.sdk` I'm afraid.  This was in effect a completely fresh start in an attempt to deliver a more trimmed down, maintainable library that tries to be a minimal layer on top of MQTT to support WIoTP specific workflow.

The way I would personally handle migration would be like so (e.g. a device client):
- Take https://github.com/ibm-watson-iot/iot-java/tree/master/samples/oshi as your starting point for a fresh project.  This will set up the framework for running the device client
- Re-implement [OshiData](https://github.com/ibm-watson-iot/iot-java/blob/master/samples/oshi/src/main/java/com/ibm/wiotp/samples/oshi/OshiData.java) to represent your device's data model based on your current device code
- The bulk of [OshiDevice](https://github.com/ibm-watson-iot/iot-java/blob/master/samples/oshi/src/main/java/com/ibm/wiotp/samples/oshi/OshiDevice.java) should not require any changes, just re-implement `createOshiData()` using whatever logic exists in your current device to generate the data it sends
- Optionally refactor the names of those classes, and then integrate these two classes with any other device code that does not directly interact with WIoTP.  
- Migration should be pretty painless if you take this approach.  The documentation isn't complete, but the configuration docs for Python apply here:
  - https://ibm-watson-iot.github.io/iot-python/application/config/
  - https://ibm-watson-iot.github.io/iot-python/device/config/

I wish had a better answer (and more time to be able to work on these SDKs), but sadly it's not to be.




Specifically reagrding this observation:

> One observation of the 0.4.0 API is that while there is .registerEventCallback the same for status messages is .setStatusCallback.

- setStatusCallback uses set because it's singular .. you set the callback for status messages
- registerEventCallback uses register because mutliple are permitted, which should (I haven't checked) be consistent with registerCommandCallback which also allows more than one to be registered.

This is because every message the statuscallback recieves will be in a fixed format (defined by WIoTP), whereas commands and events can come in all kinds of shapes and sizes, and rather than having to implement one callback that can handle every possible type of event or command, you will register different callbacks to handle specific commands/events ...

Again, I wish I had the time to get the docs in a good shape, but if you look at the code here hopefully this explains it somewhat:

https://github.com/ibm-watson-iot/iot-java/blob/f28412f5d9d069330fcb5d675094140e31c57c7d/src/main/java/com/ibm/wiotp/sdk/device/DeviceClient.java#L188

If you wanted to support 5 different commands in your device you would do something like:

```
device.registerCommandCallback(command1)
device.registerCommandCallback(command2)
device.registerCommandCallback(command3)
device.registerCommandCallback(command4)
```

Where command1,2,3,4 all implement the interface [CommandCallback](https://github.com/ibm-watson-iot/iot-java/blob/master/src/main/java/com/ibm/wiotp/sdk/device/CommandCallback.java)


It's not dealing with CommandCallback, but the application handling of EventCallback work exactly the same way.  See the sample here: https://github.com/ibm-watson-iot/iot-java/blob/master/samples/oshi/src/main/java/com/ibm/wiotp/samples/oshi/OshiApp.java


```
client.registerEventCallback(new MyEventCallback());


private class MyEventCallback implements EventCallback<OshiData> {
	@Override
	public void processEvent(Event<OshiData> evt) {
		System.out.println(evt.toString());
	}
	@Override
	public Class<OshiData> getMessageClass() {
		return OshiData.class;
	}
}
```

The eventcallback will only fire for an event defined by OshiData.  This sharing of the data model between the application and device is the main benefit we aim to bring via the Java SDK.

If you write the data model (or re-use an existing model) that implement implements `MessageInterface<MyClass>` that model becomes the common way to interact with the event data in both the application and the device, and you don't need to worry about how the object class was transmitted over the wire at all.  Which should allow both application and device developers to spend less time worry about MQTT payload and topics and more time working with the event data, which is what they should be doing imo.

Hopefully this answers your original question :+1:
